# config file version
apiVersion: 1

deleteDatasources:
  - name: loki

datasources:
- name: loki
  uid: loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false

- name: Prometheus
  uid: prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  
