global:
  scrape_interval: 15s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus:9090

- job_name: 'blackbox_exporter'
  static_configs:
  - targets: 
    - 'blackbox-exporter:9115'

- job_name: cadvisor
  static_configs:
  - targets:
    - 

- job_name: 'node'
  static_configs:
  - targets:
    - 

- job_name: 'blackbox'
  scrape_interval: 1m
  metrics_path: /probe
  params:
    module: [http_2xx]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115
  static_configs:
  - targets:
    - 
