apiVersion: 1

templates:
  - orgID: 1
    
    name: mail.subject

    editable: true

    template: |
      {{ define "mail.subject" }}
      {{ if gt (len .Alerts.Firing) 0 }}
        🚨 {{ len .Alerts.Firing }} firing alert(s) from Bahmni
      {{ else if gt (len .Alerts.Resolved) 0 }}
        ✅ {{ len .Alerts.Resolved }} resolved alert(s) from Bahmni
      {{ else }}
        🎉 No alerts from Bahmni! 🎉
      {{ end }}
      {{ end }}