apiVersion: 1
policies:
    - orgId: 1
      receiver: "Default Email"
      group_by:
        - severity
      routes:
        - receiver: "Critical High Email"
          object_matchers:
            - - severity
              - =
              - critical
            - - severity
              - =
              - high
      group_interval: 10s
      repeat_interval: 2h
